### ISSUE TITLE
TODO for 1.0.0

### ISSUE THREAD

**Issue by summerstyle** [summerstyle/summer#13]
- [ ] Change license from GPL3 to MIT
- [ ] Use app.js for interface of editor
- [ ] Move all areas code to libCoords.js
